from typing import List


class ShortcutHelpHandler:
    @staticmethod
    def get_lines() -> List[str]:
        return [
            "Shortcuts",
            "",
            "Global",
            "  Ctrl+C / Ctrl+X - exit",
            "  Ctrl+S (df) - save",
            "  Ctrl+T (df) - save & exit",
            "  ? - show shortcuts",
            "",
            "Overlay (output)",
            "  Esc / q / Enter - close",
            "  j / k - scroll",
            "  Ctrl+J / Ctrl+K - half-page down/up",
            "  ,j / ,k - bottom/top",
            "",
            "Command bar",
            "  : (from df) - enter",
            "  Enter - execute",
            "  Esc - cancel",
            "  Ctrl+P / Ctrl+N - history prev/next",
            "  Backspace, Left/Right, Home/End - edit/move",
            "  Tab - apply completion/expansion",
            "  Emacs-style: Alt+F/B (word fwd/back), Ctrl+W (delete word), Ctrl+U (kill to start), Ctrl+H/D (move left/right), Ctrl+A/E (line start/end)",
            "",
            "DF normal",
            "  (Numeric prefixes) h/j/k/l, Ctrl+J/K/H/L, ,ira/irb, ,dr, ,x+, ,x-",
            "  h / j / k / l - move",
            "  Ctrl+J / Ctrl+K - jump ~5% rows down/up",
            "  Ctrl+H / Ctrl+L - jump ~20% cols left/right",
            "  : - open command bar",
            "  i - edit current cell in vim (current terminal)",
            "  x - clear current cell",
            "  , i r a - insert row above",
            "  , i r b - insert row below",
            "  , d r - delete row",
            "  , i c a - insert column after (prompt name + dtype)",
            "  , i c b - insert column before (prompt name + dtype)",
            "  , d c - delete column",
            "  , r n c - rename column",
            "  ,xr - expand/collapse current row",
            "  ,xar - expand/collapse all rows",
            "  ,xc - collapse all expansions",
            "  ,x+ - increase row lines",
            "  ,x- - decrease row lines",
            "  u - undo",
            "  r - redo",
            "  . - repeat last change (not for column ops or command bar)",
            "  , h - go to first column",
            "  , l - go to last column",
            "  , j - go to last row",
            "  , k - go to first row",
            "  , y a - copy df to clipboard (TSV)",
            "  , y c - copy current cell to clipboard",
            "  , p j - preview current cell as pretty JSON (read-only Vim)",
            "  ? - shortcuts",
            "",
            "Save prompt",
            "  Enter - save (requires .csv or .parquet)",
            "  Esc - cancel",
            "  Backspace, Left/Right, Home/End - edit path",
            "",
            "Column prompt",
            "  Enter - confirm name/dtype",
            "  Esc - cancel",
            "  Backspace, Left/Right, Home/End - edit",
            "",
            "Loading screen",
            "  Ctrl+X - abort loading",
        ]
