from typing import List


class ShortcutHelpHandler:
    @staticmethod
    def get_lines() -> List[str]:
        return [
            "Shortcuts",
            "",
            "Global",
            "  Ctrl+C / Ctrl+X - exit",
            "  Ctrl+S (df) - save",
            "  Ctrl+T (df) - save & exit",
            "  ? - show shortcuts",
            "",
            "Overlay (output)",
            "  Esc / q / Enter - close",
            "  j / k - scroll",
            "",
            "Command bar",
            "  : (from df) - enter",
            "  Enter / Ctrl+E - execute",
            "  Esc - cancel",
            "  Ctrl+P / Ctrl+N - history prev/next",
            "  Backspace, Left/Right, Home/End - edit/move",
            "",
            "DF normal",
            "  h / j / k / l - move",
            "  Ctrl+J / Ctrl+K - jump ~5% rows down/up",
            "  Ctrl+H / Ctrl+L - jump ~20% cols left/right",
            "  : - open command bar",
            "  n - enter cell_normal on current cell (leader sequences are shown in status)",
            "  i - edit cell (preload)",
            "  , e - edit cell (preload)",
            "  , c c - edit cell empty",
            "  x - clear current cell",
            "  , i r a - insert row above",
            "  , i r b - insert row below",
            "  , d r - delete row",
            "  , i c a - insert column after (prompt name + dtype)",
            "  , i c b - insert column before (prompt name + dtype)",
            "  , d c - delete column",
            "  , r n c - rename column",
            "  ,+rl - increase row lines",
            "  ,-rl - decrease row lines",
            "  , h - go to first column",
            "  , l - go to last column",
            "  , j - go to last row",
            "  , k - go to first row",
            "  , y - copy df to clipboard (TSV)",
            "  ? - shortcuts",
            "",
            "DF cell_insert",
            "  Type to edit; Backspace deletes; Esc commits to cell_normal",
            "",
            "DF cell_normal",
            "  h / l - move cursor within buffer; 0 / $ - line edges; w / b - word nav",
            "  , e / , c c",
            "  i - insert; Esc - back to df normal",
        ]
